// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: solana.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SolanaService_Health_FullMethodName = "/maruvo.SolanaService/Health"
)

// SolanaServiceClient is the client API for SolanaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SolanaServiceClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type solanaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSolanaServiceClient(cc grpc.ClientConnInterface) SolanaServiceClient {
	return &solanaServiceClient{cc}
}

func (c *solanaServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, SolanaService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SolanaServiceServer is the server API for SolanaService service.
// All implementations must embed UnimplementedSolanaServiceServer
// for forward compatibility.
type SolanaServiceServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedSolanaServiceServer()
}

// UnimplementedSolanaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSolanaServiceServer struct{}

func (UnimplementedSolanaServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSolanaServiceServer) mustEmbedUnimplementedSolanaServiceServer() {}
func (UnimplementedSolanaServiceServer) testEmbeddedByValue()                       {}

// UnsafeSolanaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SolanaServiceServer will
// result in compilation errors.
type UnsafeSolanaServiceServer interface {
	mustEmbedUnimplementedSolanaServiceServer()
}

func RegisterSolanaServiceServer(s grpc.ServiceRegistrar, srv SolanaServiceServer) {
	// If the following call panics, it indicates UnimplementedSolanaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SolanaService_ServiceDesc, srv)
}

func _SolanaService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolanaServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolanaService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolanaServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SolanaService_ServiceDesc is the grpc.ServiceDesc for SolanaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SolanaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "maruvo.SolanaService",
	HandlerType: (*SolanaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _SolanaService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "solana.proto",
}
