// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: solana.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SolanaService_Health_FullMethodName            = "/maruvo.SolanaService/Health"
	SolanaService_Demo_FullMethodName              = "/maruvo.SolanaService/Demo"
	SolanaService_PrepareEscrow_FullMethodName     = "/maruvo.SolanaService/PrepareEscrow"
	SolanaService_SubmitEscrow_FullMethodName      = "/maruvo.SolanaService/SubmitEscrow"
	SolanaService_CheckEscrow_FullMethodName       = "/maruvo.SolanaService/CheckEscrow"
	SolanaService_PrepareSettlement_FullMethodName = "/maruvo.SolanaService/PrepareSettlement"
	SolanaService_CheckSettlement_FullMethodName   = "/maruvo.SolanaService/CheckSettlement"
)

// SolanaServiceClient is the client API for SolanaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SolanaServiceClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Demo(ctx context.Context, in *DemoRequest, opts ...grpc.CallOption) (*DemoResponse, error)
	PrepareEscrow(ctx context.Context, in *PrepareEscrowRequest, opts ...grpc.CallOption) (*PreparedEscrow, error)
	SubmitEscrow(ctx context.Context, in *SubmitEscrowRequest, opts ...grpc.CallOption) (*SubmittedEscrow, error)
	CheckEscrow(ctx context.Context, in *CheckEscrowRequest, opts ...grpc.CallOption) (*EscrowState, error)
	PrepareSettlement(ctx context.Context, in *PrepareSettlementRequest, opts ...grpc.CallOption) (*PreparedSettlement, error)
	CheckSettlement(ctx context.Context, in *CheckSettlementRequest, opts ...grpc.CallOption) (*SettlementState, error)
}

type solanaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSolanaServiceClient(cc grpc.ClientConnInterface) SolanaServiceClient {
	return &solanaServiceClient{cc}
}

func (c *solanaServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, SolanaService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *solanaServiceClient) Demo(ctx context.Context, in *DemoRequest, opts ...grpc.CallOption) (*DemoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DemoResponse)
	err := c.cc.Invoke(ctx, SolanaService_Demo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *solanaServiceClient) PrepareEscrow(ctx context.Context, in *PrepareEscrowRequest, opts ...grpc.CallOption) (*PreparedEscrow, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreparedEscrow)
	err := c.cc.Invoke(ctx, SolanaService_PrepareEscrow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *solanaServiceClient) SubmitEscrow(ctx context.Context, in *SubmitEscrowRequest, opts ...grpc.CallOption) (*SubmittedEscrow, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmittedEscrow)
	err := c.cc.Invoke(ctx, SolanaService_SubmitEscrow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *solanaServiceClient) CheckEscrow(ctx context.Context, in *CheckEscrowRequest, opts ...grpc.CallOption) (*EscrowState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EscrowState)
	err := c.cc.Invoke(ctx, SolanaService_CheckEscrow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *solanaServiceClient) PrepareSettlement(ctx context.Context, in *PrepareSettlementRequest, opts ...grpc.CallOption) (*PreparedSettlement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreparedSettlement)
	err := c.cc.Invoke(ctx, SolanaService_PrepareSettlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *solanaServiceClient) CheckSettlement(ctx context.Context, in *CheckSettlementRequest, opts ...grpc.CallOption) (*SettlementState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettlementState)
	err := c.cc.Invoke(ctx, SolanaService_CheckSettlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SolanaServiceServer is the server API for SolanaService service.
// All implementations must embed UnimplementedSolanaServiceServer
// for forward compatibility.
type SolanaServiceServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Demo(context.Context, *DemoRequest) (*DemoResponse, error)
	PrepareEscrow(context.Context, *PrepareEscrowRequest) (*PreparedEscrow, error)
	SubmitEscrow(context.Context, *SubmitEscrowRequest) (*SubmittedEscrow, error)
	CheckEscrow(context.Context, *CheckEscrowRequest) (*EscrowState, error)
	PrepareSettlement(context.Context, *PrepareSettlementRequest) (*PreparedSettlement, error)
	CheckSettlement(context.Context, *CheckSettlementRequest) (*SettlementState, error)
	mustEmbedUnimplementedSolanaServiceServer()
}

// UnimplementedSolanaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSolanaServiceServer struct{}

func (UnimplementedSolanaServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSolanaServiceServer) Demo(context.Context, *DemoRequest) (*DemoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Demo not implemented")
}
func (UnimplementedSolanaServiceServer) PrepareEscrow(context.Context, *PrepareEscrowRequest) (*PreparedEscrow, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareEscrow not implemented")
}
func (UnimplementedSolanaServiceServer) SubmitEscrow(context.Context, *SubmitEscrowRequest) (*SubmittedEscrow, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitEscrow not implemented")
}
func (UnimplementedSolanaServiceServer) CheckEscrow(context.Context, *CheckEscrowRequest) (*EscrowState, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckEscrow not implemented")
}
func (UnimplementedSolanaServiceServer) PrepareSettlement(context.Context, *PrepareSettlementRequest) (*PreparedSettlement, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareSettlement not implemented")
}
func (UnimplementedSolanaServiceServer) CheckSettlement(context.Context, *CheckSettlementRequest) (*SettlementState, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckSettlement not implemented")
}
func (UnimplementedSolanaServiceServer) mustEmbedUnimplementedSolanaServiceServer() {}
func (UnimplementedSolanaServiceServer) testEmbeddedByValue()                       {}

// UnsafeSolanaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SolanaServiceServer will
// result in compilation errors.
type UnsafeSolanaServiceServer interface {
	mustEmbedUnimplementedSolanaServiceServer()
}

func RegisterSolanaServiceServer(s grpc.ServiceRegistrar, srv SolanaServiceServer) {
	// If the following call panics, it indicates UnimplementedSolanaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SolanaService_ServiceDesc, srv)
}

func _SolanaService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolanaServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolanaService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolanaServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SolanaService_Demo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DemoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolanaServiceServer).Demo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolanaService_Demo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolanaServiceServer).Demo(ctx, req.(*DemoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SolanaService_PrepareEscrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareEscrowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolanaServiceServer).PrepareEscrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolanaService_PrepareEscrow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolanaServiceServer).PrepareEscrow(ctx, req.(*PrepareEscrowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SolanaService_SubmitEscrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitEscrowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolanaServiceServer).SubmitEscrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolanaService_SubmitEscrow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolanaServiceServer).SubmitEscrow(ctx, req.(*SubmitEscrowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SolanaService_CheckEscrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckEscrowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolanaServiceServer).CheckEscrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolanaService_CheckEscrow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolanaServiceServer).CheckEscrow(ctx, req.(*CheckEscrowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SolanaService_PrepareSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareSettlementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolanaServiceServer).PrepareSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolanaService_PrepareSettlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolanaServiceServer).PrepareSettlement(ctx, req.(*PrepareSettlementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SolanaService_CheckSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckSettlementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolanaServiceServer).CheckSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolanaService_CheckSettlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolanaServiceServer).CheckSettlement(ctx, req.(*CheckSettlementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SolanaService_ServiceDesc is the grpc.ServiceDesc for SolanaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SolanaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "maruvo.SolanaService",
	HandlerType: (*SolanaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _SolanaService_Health_Handler,
		},
		{
			MethodName: "Demo",
			Handler:    _SolanaService_Demo_Handler,
		},
		{
			MethodName: "PrepareEscrow",
			Handler:    _SolanaService_PrepareEscrow_Handler,
		},
		{
			MethodName: "SubmitEscrow",
			Handler:    _SolanaService_SubmitEscrow_Handler,
		},
		{
			MethodName: "CheckEscrow",
			Handler:    _SolanaService_CheckEscrow_Handler,
		},
		{
			MethodName: "PrepareSettlement",
			Handler:    _SolanaService_PrepareSettlement_Handler,
		},
		{
			MethodName: "CheckSettlement",
			Handler:    _SolanaService_CheckSettlement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "solana.proto",
}
