// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentGrant = `-- name: CreateAgentGrant :one
INSERT INTO agent_grants (id, owner_id, post_id, name, token_hash, permissions, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, owner_id, post_id, name, token_hash, permissions, expires_at, revoked_at, created_at
`

type CreateAgentGrantParams struct {
	ID          pgtype.UUID        `json:"id"`
	OwnerID     int64              `json:"owner_id"`
	PostID      int64              `json:"post_id"`
	Name        string             `json:"name"`
	TokenHash   string             `json:"token_hash"`
	Permissions []string           `json:"permissions"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAgentGrant(ctx context.Context, arg CreateAgentGrantParams) (AgentGrant, error) {
	row := q.db.QueryRow(ctx, createAgentGrant,
		arg.ID,
		arg.OwnerID,
		arg.PostID,
		arg.Name,
		arg.TokenHash,
		arg.Permissions,
		arg.ExpiresAt,
	)
	var i AgentGrant
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.PostID,
		&i.Name,
		&i.TokenHash,
		&i.Permissions,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentGrants = `-- name: ListAgentGrants :many
SELECT id, owner_id, post_id, name, token_hash, permissions, expires_at, revoked_at, created_at FROM agent_grants WHERE owner_id = $1 AND post_id = $2 ORDER BY created_at DESC, id LIMIT 100
`

type ListAgentGrantsParams struct {
	OwnerID int64 `json:"owner_id"`
	PostID  int64 `json:"post_id"`
}

func (q *Queries) ListAgentGrants(ctx context.Context, arg ListAgentGrantsParams) ([]AgentGrant, error) {
	rows, err := q.db.Query(ctx, listAgentGrants, arg.OwnerID, arg.PostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentGrant
	for rows.Next() {
		var i AgentGrant
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.PostID,
			&i.Name,
			&i.TokenHash,
			&i.Permissions,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveAgentGrant = `-- name: LockActiveAgentGrant :one
SELECT id, owner_id, post_id, name, token_hash, permissions, expires_at, revoked_at, created_at FROM agent_grants WHERE id = $1 AND revoked_at IS NULL AND expires_at > NOW()
FOR SHARE
`

func (q *Queries) LockActiveAgentGrant(ctx context.Context, id pgtype.UUID) (AgentGrant, error) {
	row := q.db.QueryRow(ctx, lockActiveAgentGrant, id)
	var i AgentGrant
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.PostID,
		&i.Name,
		&i.TokenHash,
		&i.Permissions,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const resolveAgentGrant = `-- name: ResolveAgentGrant :one
SELECT g.id, g.owner_id, g.post_id, g.name, g.token_hash, g.permissions, g.expires_at, g.revoked_at, g.created_at FROM agent_grants g JOIN users u ON u.id = g.owner_id
WHERE g.token_hash = $1 AND g.revoked_at IS NULL AND g.expires_at > NOW()
AND NOT EXISTS (SELECT 1 FROM post_agent_controls c
    WHERE c.post_id = g.post_id AND c.owner_id = g.owner_id AND c.mode = 'manual')
`

func (q *Queries) ResolveAgentGrant(ctx context.Context, tokenHash string) (AgentGrant, error) {
	row := q.db.QueryRow(ctx, resolveAgentGrant, tokenHash)
	var i AgentGrant
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.PostID,
		&i.Name,
		&i.TokenHash,
		&i.Permissions,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAgentGrant = `-- name: RevokeAgentGrant :one
UPDATE agent_grants SET revoked_at = COALESCE(revoked_at, NOW())
WHERE id = $1 AND owner_id = $2 RETURNING id, owner_id, post_id, name, token_hash, permissions, expires_at, revoked_at, created_at
`

type RevokeAgentGrantParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID int64       `json:"owner_id"`
}

func (q *Queries) RevokeAgentGrant(ctx context.Context, arg RevokeAgentGrantParams) (AgentGrant, error) {
	row := q.db.QueryRow(ctx, revokeAgentGrant, arg.ID, arg.OwnerID)
	var i AgentGrant
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.PostID,
		&i.Name,
		&i.TokenHash,
		&i.Permissions,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}
