// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_control.sql

package db

import (
	"context"
)

const ensureAgentControl = `-- name: EnsureAgentControl :exec
INSERT INTO post_agent_controls (post_id, owner_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type EnsureAgentControlParams struct {
	PostID  int64 `json:"post_id"`
	OwnerID int64 `json:"owner_id"`
}

func (q *Queries) EnsureAgentControl(ctx context.Context, arg EnsureAgentControlParams) error {
	_, err := q.db.Exec(ctx, ensureAgentControl, arg.PostID, arg.OwnerID)
	return err
}

const getAgentControl = `-- name: GetAgentControl :one
SELECT post_id, owner_id, mode, updated_at FROM post_agent_controls WHERE post_id = $1 AND owner_id = $2
`

type GetAgentControlParams struct {
	PostID  int64 `json:"post_id"`
	OwnerID int64 `json:"owner_id"`
}

func (q *Queries) GetAgentControl(ctx context.Context, arg GetAgentControlParams) (PostAgentControl, error) {
	row := q.db.QueryRow(ctx, getAgentControl, arg.PostID, arg.OwnerID)
	var i PostAgentControl
	err := row.Scan(
		&i.PostID,
		&i.OwnerID,
		&i.Mode,
		&i.UpdatedAt,
	)
	return i, err
}

const lockAgentControl = `-- name: LockAgentControl :one
SELECT post_id, owner_id, mode, updated_at FROM post_agent_controls WHERE post_id = $1 AND owner_id = $2 FOR UPDATE
`

type LockAgentControlParams struct {
	PostID  int64 `json:"post_id"`
	OwnerID int64 `json:"owner_id"`
}

func (q *Queries) LockAgentControl(ctx context.Context, arg LockAgentControlParams) (PostAgentControl, error) {
	row := q.db.QueryRow(ctx, lockAgentControl, arg.PostID, arg.OwnerID)
	var i PostAgentControl
	err := row.Scan(
		&i.PostID,
		&i.OwnerID,
		&i.Mode,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeTaskAgentGrants = `-- name: RevokeTaskAgentGrants :execrows
UPDATE agent_grants SET revoked_at = NOW()
WHERE post_id = $1 AND owner_id = $2 AND revoked_at IS NULL AND expires_at > NOW()
`

type RevokeTaskAgentGrantsParams struct {
	PostID  int64 `json:"post_id"`
	OwnerID int64 `json:"owner_id"`
}

func (q *Queries) RevokeTaskAgentGrants(ctx context.Context, arg RevokeTaskAgentGrantsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeTaskAgentGrants, arg.PostID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAgentControl = `-- name: SetAgentControl :one
UPDATE post_agent_controls SET mode = $3, updated_at = clock_timestamp()
WHERE post_id = $1 AND owner_id = $2 RETURNING post_id, owner_id, mode, updated_at
`

type SetAgentControlParams struct {
	PostID  int64  `json:"post_id"`
	OwnerID int64  `json:"owner_id"`
	Mode    string `json:"mode"`
}

func (q *Queries) SetAgentControl(ctx context.Context, arg SetAgentControlParams) (PostAgentControl, error) {
	row := q.db.QueryRow(ctx, setAgentControl, arg.PostID, arg.OwnerID, arg.Mode)
	var i PostAgentControl
	err := row.Scan(
		&i.PostID,
		&i.OwnerID,
		&i.Mode,
		&i.UpdatedAt,
	)
	return i, err
}
