// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package db

import (
	"context"
	"encoding/json"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const archiveWorkspaceMessages = `-- name: ArchiveWorkspaceMessages :batchexec
SELECT archive_workspace_message($1::bigint, $2::bigint,
    $3::text, $4::jsonb, $5::timestamptz)
`

type ArchiveWorkspaceMessagesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type ArchiveWorkspaceMessagesParams struct {
	PostID    int64              `json:"post_id"`
	ActorID   pgtype.Int8        `json:"actor_id"`
	StreamID  string             `json:"stream_id"`
	Data      json.RawMessage    `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ArchiveWorkspaceMessages(ctx context.Context, arg []ArchiveWorkspaceMessagesParams) *ArchiveWorkspaceMessagesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.PostID,
			a.ActorID,
			a.StreamID,
			a.Data,
			a.CreatedAt,
		}
		batch.Queue(archiveWorkspaceMessages, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &ArchiveWorkspaceMessagesBatchResults{br, len(arg), false}
}

func (b *ArchiveWorkspaceMessagesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *ArchiveWorkspaceMessagesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
