// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chats.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAgentChat = `-- name: GetAgentChat :one
SELECT snapshot FROM agent_chats WHERE user_id = $1 AND profile = $2 AND id = $3
`

type GetAgentChatParams struct {
	UserID  int64  `json:"user_id"`
	Profile string `json:"profile"`
	ID      string `json:"id"`
}

func (q *Queries) GetAgentChat(ctx context.Context, arg GetAgentChatParams) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getAgentChat, arg.UserID, arg.Profile, arg.ID)
	var snapshot json.RawMessage
	err := row.Scan(&snapshot)
	return snapshot, err
}

const listAgentChats = `-- name: ListAgentChats :many
SELECT id, title, directory, provider, model, created_at, updated_at, archived
FROM agent_chats WHERE user_id = $1 AND profile = $2
ORDER BY updated_at DESC, id LIMIT 200
`

type ListAgentChatsParams struct {
	UserID  int64  `json:"user_id"`
	Profile string `json:"profile"`
}

type ListAgentChatsRow struct {
	ID        string             `json:"id"`
	Title     string             `json:"title"`
	Directory string             `json:"directory"`
	Provider  string             `json:"provider"`
	Model     string             `json:"model"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Archived  bool               `json:"archived"`
}

func (q *Queries) ListAgentChats(ctx context.Context, arg ListAgentChatsParams) ([]ListAgentChatsRow, error) {
	rows, err := q.db.Query(ctx, listAgentChats, arg.UserID, arg.Profile)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentChatsRow
	for rows.Next() {
		var i ListAgentChatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Directory,
			&i.Provider,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveAgentChat = `-- name: SaveAgentChat :exec
INSERT INTO agent_chats (user_id, profile, id, title, directory, provider, model, created_at, updated_at, archived, snapshot, revision)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (user_id, profile, id) DO UPDATE SET
    title = EXCLUDED.title, provider = EXCLUDED.provider, model = EXCLUDED.model,
    updated_at = EXCLUDED.updated_at, archived = EXCLUDED.archived, snapshot = EXCLUDED.snapshot,
    revision = EXCLUDED.revision
WHERE agent_chats.revision <= EXCLUDED.revision
    AND agent_chats.directory = EXCLUDED.directory AND agent_chats.created_at = EXCLUDED.created_at
`

type SaveAgentChatParams struct {
	UserID    int64              `json:"user_id"`
	Profile   string             `json:"profile"`
	ID        string             `json:"id"`
	Title     string             `json:"title"`
	Directory string             `json:"directory"`
	Provider  string             `json:"provider"`
	Model     string             `json:"model"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Archived  bool               `json:"archived"`
	Snapshot  json.RawMessage    `json:"snapshot"`
	Revision  int64              `json:"revision"`
}

func (q *Queries) SaveAgentChat(ctx context.Context, arg SaveAgentChatParams) error {
	_, err := q.db.Exec(ctx, saveAgentChat,
		arg.UserID,
		arg.Profile,
		arg.ID,
		arg.Title,
		arg.Directory,
		arg.Provider,
		arg.Model,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Archived,
		arg.Snapshot,
		arg.Revision,
	)
	return err
}
