// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deadlines.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const overdueTaskCandidates = `-- name: OverdueTaskCandidates :many
SELECT p.id FROM posts p JOIN post_workspaces w ON w.post_id = p.id
WHERE p.id > $1 AND (
    (p.status = 'negotiating' AND p.fund_by <= NOW())
    OR (p.status = 'in_progress' AND w.review_state IN ('working', 'changes_requested') AND p.deliver_by <= NOW())
    OR (p.status = 'in_progress' AND w.review_state = 'submitted' AND w.review_by <= NOW()))
ORDER BY p.id LIMIT 100
`

func (q *Queries) OverdueTaskCandidates(ctx context.Context, id int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, overdueTaskCandidates, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDeadlineNotice = `-- name: RecordDeadlineNotice :one
INSERT INTO task_deadline_notices(post_id, stage, submission_version, due_at)
VALUES ($1, $2, $3, $4) ON CONFLICT DO NOTHING RETURNING post_id
`

type RecordDeadlineNoticeParams struct {
	PostID            int64              `json:"post_id"`
	Stage             string             `json:"stage"`
	SubmissionVersion int64              `json:"submission_version"`
	DueAt             pgtype.Timestamptz `json:"due_at"`
}

func (q *Queries) RecordDeadlineNotice(ctx context.Context, arg RecordDeadlineNoticeParams) (int64, error) {
	row := q.db.QueryRow(ctx, recordDeadlineNotice,
		arg.PostID,
		arg.Stage,
		arg.SubmissionVersion,
		arg.DueAt,
	)
	var post_id int64
	err := row.Scan(&post_id)
	return post_id, err
}

const taskDeadlineSnapshots = `-- name: TaskDeadlineSnapshots :many
SELECT p.id, p.status, p.end_time, p.fund_by, p.deliver_by,
    COALESCE(w.review_state, '')::text AS review_state, w.review_by, w.submitted_at
FROM posts p LEFT JOIN post_workspaces w ON w.post_id = p.id
WHERE p.id = ANY($1::bigint[])
`

type TaskDeadlineSnapshotsRow struct {
	ID          int64              `json:"id"`
	Status      PostStatus         `json:"status"`
	EndTime     pgtype.Timestamptz `json:"end_time"`
	FundBy      pgtype.Timestamptz `json:"fund_by"`
	DeliverBy   pgtype.Timestamptz `json:"deliver_by"`
	ReviewState string             `json:"review_state"`
	ReviewBy    pgtype.Timestamptz `json:"review_by"`
	SubmittedAt pgtype.Timestamptz `json:"submitted_at"`
}

func (q *Queries) TaskDeadlineSnapshots(ctx context.Context, dollar_1 []int64) ([]TaskDeadlineSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, taskDeadlineSnapshots, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskDeadlineSnapshotsRow
	for rows.Next() {
		var i TaskDeadlineSnapshotsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.EndTime,
			&i.FundBy,
			&i.DeliverBy,
			&i.ReviewState,
			&i.ReviewBy,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
