// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: escrow.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptPost = `-- name: AcceptPost :one
UPDATE posts SET accepted_by = $1, accepted_at = NOW(),
    poster_wallet = poster.address, worker_wallet = worker.address,
    status = 'negotiating', updated_at = NOW()
FROM wallets AS poster, wallets AS worker
WHERE posts.id = $2 AND posts.user_id <> $1
    AND posts.status = 'open' AND posts.accepted_by IS NULL AND posts.end_time > NOW()
    AND poster.user_id = posts.user_id AND worker.user_id = $1
RETURNING posts.id, posts.user_id, posts.title, posts.cost_lamports, posts.end_time, posts.status, posts.level, posts.created_at, posts.updated_at, posts.accepted_by, posts.accepted_at, posts.poster_wallet, posts.worker_wallet, posts.description, posts.acceptance_criteria, posts.input_files, posts.expected_outputs
`

type AcceptPostParams struct {
	WorkerID pgtype.Int8 `json:"worker_id"`
	PostID   int64       `json:"post_id"`
}

func (q *Queries) AcceptPost(ctx context.Context, arg AcceptPostParams) (Post, error) {
	row := q.db.QueryRow(ctx, acceptPost, arg.WorkerID, arg.PostID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CostLamports,
		&i.EndTime,
		&i.Status,
		&i.Level,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedBy,
		&i.AcceptedAt,
		&i.PosterWallet,
		&i.WorkerWallet,
		&i.Description,
		&i.AcceptanceCriteria,
		&i.InputFiles,
		&i.ExpectedOutputs,
	)
	return i, err
}

const consumeWalletChallenge = `-- name: ConsumeWalletChallenge :execrows
DELETE FROM wallet_challenges WHERE user_id = $1 AND message = $2 AND expires_at > NOW()
`

type ConsumeWalletChallengeParams struct {
	UserID  int64  `json:"user_id"`
	Message string `json:"message"`
}

func (q *Queries) ConsumeWalletChallenge(ctx context.Context, arg ConsumeWalletChallengeParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeWalletChallenge, arg.UserID, arg.Message)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPost = `-- name: GetPost :one
SELECT id, user_id, title, cost_lamports, end_time, status, level, created_at, updated_at, accepted_by, accepted_at, poster_wallet, worker_wallet, description, acceptance_criteria, input_files, expected_outputs FROM posts WHERE id = $1
`

func (q *Queries) GetPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CostLamports,
		&i.EndTime,
		&i.Status,
		&i.Level,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedBy,
		&i.AcceptedAt,
		&i.PosterWallet,
		&i.WorkerWallet,
		&i.Description,
		&i.AcceptanceCriteria,
		&i.InputFiles,
		&i.ExpectedOutputs,
	)
	return i, err
}

const getPostEscrow = `-- name: GetPostEscrow :one
SELECT post_id, address, program_id, reviewer, network, transaction, signature, last_valid_block_height, fee_lamports, storage_lamports, state, updated_at FROM post_escrows WHERE post_id = $1
`

func (q *Queries) GetPostEscrow(ctx context.Context, postID int64) (PostEscrow, error) {
	row := q.db.QueryRow(ctx, getPostEscrow, postID)
	var i PostEscrow
	err := row.Scan(
		&i.PostID,
		&i.Address,
		&i.ProgramID,
		&i.Reviewer,
		&i.Network,
		&i.Transaction,
		&i.Signature,
		&i.LastValidBlockHeight,
		&i.FeeLamports,
		&i.StorageLamports,
		&i.State,
		&i.UpdatedAt,
	)
	return i, err
}

const getWallet = `-- name: GetWallet :one
SELECT user_id, address, linked_at FROM wallets WHERE user_id = $1
`

func (q *Queries) GetWallet(ctx context.Context, userID int64) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWallet, userID)
	var i Wallet
	err := row.Scan(&i.UserID, &i.Address, &i.LinkedAt)
	return i, err
}

const getWalletChallenge = `-- name: GetWalletChallenge :one
SELECT user_id, address, message, expires_at FROM wallet_challenges WHERE user_id = $1 AND expires_at > NOW()
`

func (q *Queries) GetWalletChallenge(ctx context.Context, userID int64) (WalletChallenge, error) {
	row := q.db.QueryRow(ctx, getWalletChallenge, userID)
	var i WalletChallenge
	err := row.Scan(
		&i.UserID,
		&i.Address,
		&i.Message,
		&i.ExpiresAt,
	)
	return i, err
}

const linkWallet = `-- name: LinkWallet :one
INSERT INTO wallets (user_id, address) VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET address = EXCLUDED.address
WHERE wallets.address = EXCLUDED.address
RETURNING user_id, address, linked_at
`

type LinkWalletParams struct {
	UserID  int64  `json:"user_id"`
	Address string `json:"address"`
}

func (q *Queries) LinkWallet(ctx context.Context, arg LinkWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, linkWallet, arg.UserID, arg.Address)
	var i Wallet
	err := row.Scan(&i.UserID, &i.Address, &i.LinkedAt)
	return i, err
}

const lockPost = `-- name: LockPost :one
SELECT id, user_id, title, cost_lamports, end_time, status, level, created_at, updated_at, accepted_by, accepted_at, poster_wallet, worker_wallet, description, acceptance_criteria, input_files, expected_outputs FROM posts WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRow(ctx, lockPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CostLamports,
		&i.EndTime,
		&i.Status,
		&i.Level,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedBy,
		&i.AcceptedAt,
		&i.PosterWallet,
		&i.WorkerWallet,
		&i.Description,
		&i.AcceptanceCriteria,
		&i.InputFiles,
		&i.ExpectedOutputs,
	)
	return i, err
}

const markEscrowSubmitted = `-- name: MarkEscrowSubmitted :one
UPDATE post_escrows SET signature = $2, state = 'pending', updated_at = NOW()
WHERE post_id = $1 AND transaction = $3 AND state = 'prepared' RETURNING post_id, address, program_id, reviewer, network, transaction, signature, last_valid_block_height, fee_lamports, storage_lamports, state, updated_at
`

type MarkEscrowSubmittedParams struct {
	PostID      int64  `json:"post_id"`
	Signature   string `json:"signature"`
	Transaction string `json:"transaction"`
}

func (q *Queries) MarkEscrowSubmitted(ctx context.Context, arg MarkEscrowSubmittedParams) (PostEscrow, error) {
	row := q.db.QueryRow(ctx, markEscrowSubmitted, arg.PostID, arg.Signature, arg.Transaction)
	var i PostEscrow
	err := row.Scan(
		&i.PostID,
		&i.Address,
		&i.ProgramID,
		&i.Reviewer,
		&i.Network,
		&i.Transaction,
		&i.Signature,
		&i.LastValidBlockHeight,
		&i.FeeLamports,
		&i.StorageLamports,
		&i.State,
		&i.UpdatedAt,
	)
	return i, err
}

const markPostFunded = `-- name: MarkPostFunded :one
UPDATE posts SET status = 'in_progress', updated_at = NOW()
WHERE id = $1 AND accepted_by IS NOT NULL AND status = 'negotiating' RETURNING id, user_id, title, cost_lamports, end_time, status, level, created_at, updated_at, accepted_by, accepted_at, poster_wallet, worker_wallet, description, acceptance_criteria, input_files, expected_outputs
`

func (q *Queries) MarkPostFunded(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRow(ctx, markPostFunded, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CostLamports,
		&i.EndTime,
		&i.Status,
		&i.Level,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedBy,
		&i.AcceptedAt,
		&i.PosterWallet,
		&i.WorkerWallet,
		&i.Description,
		&i.AcceptanceCriteria,
		&i.InputFiles,
		&i.ExpectedOutputs,
	)
	return i, err
}

const markPostSettled = `-- name: MarkPostSettled :one
UPDATE posts SET status = $2, updated_at = NOW() WHERE id = $1 AND accepted_by IS NOT NULL RETURNING id, user_id, title, cost_lamports, end_time, status, level, created_at, updated_at, accepted_by, accepted_at, poster_wallet, worker_wallet, description, acceptance_criteria, input_files, expected_outputs
`

type MarkPostSettledParams struct {
	ID     int64      `json:"id"`
	Status PostStatus `json:"status"`
}

func (q *Queries) MarkPostSettled(ctx context.Context, arg MarkPostSettledParams) (Post, error) {
	row := q.db.QueryRow(ctx, markPostSettled, arg.ID, arg.Status)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CostLamports,
		&i.EndTime,
		&i.Status,
		&i.Level,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedBy,
		&i.AcceptedAt,
		&i.PosterWallet,
		&i.WorkerWallet,
		&i.Description,
		&i.AcceptanceCriteria,
		&i.InputFiles,
		&i.ExpectedOutputs,
	)
	return i, err
}

const savePostEscrow = `-- name: SavePostEscrow :one
INSERT INTO post_escrows (post_id, address, program_id, reviewer, network, transaction, last_valid_block_height, fee_lamports, storage_lamports)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (post_id) DO UPDATE SET transaction = EXCLUDED.transaction,
    last_valid_block_height = EXCLUDED.last_valid_block_height,
    fee_lamports = EXCLUDED.fee_lamports, storage_lamports = EXCLUDED.storage_lamports,
    signature = '', state = 'prepared', updated_at = NOW()
WHERE post_escrows.state IN ('failed', 'expired')
    AND post_escrows.address = EXCLUDED.address AND post_escrows.program_id = EXCLUDED.program_id
    AND post_escrows.reviewer = EXCLUDED.reviewer AND post_escrows.network = EXCLUDED.network
RETURNING post_id, address, program_id, reviewer, network, transaction, signature, last_valid_block_height, fee_lamports, storage_lamports, state, updated_at
`

type SavePostEscrowParams struct {
	PostID               int64  `json:"post_id"`
	Address              string `json:"address"`
	ProgramID            string `json:"program_id"`
	Reviewer             string `json:"reviewer"`
	Network              string `json:"network"`
	Transaction          string `json:"transaction"`
	LastValidBlockHeight int64  `json:"last_valid_block_height"`
	FeeLamports          int64  `json:"fee_lamports"`
	StorageLamports      int64  `json:"storage_lamports"`
}

func (q *Queries) SavePostEscrow(ctx context.Context, arg SavePostEscrowParams) (PostEscrow, error) {
	row := q.db.QueryRow(ctx, savePostEscrow,
		arg.PostID,
		arg.Address,
		arg.ProgramID,
		arg.Reviewer,
		arg.Network,
		arg.Transaction,
		arg.LastValidBlockHeight,
		arg.FeeLamports,
		arg.StorageLamports,
	)
	var i PostEscrow
	err := row.Scan(
		&i.PostID,
		&i.Address,
		&i.ProgramID,
		&i.Reviewer,
		&i.Network,
		&i.Transaction,
		&i.Signature,
		&i.LastValidBlockHeight,
		&i.FeeLamports,
		&i.StorageLamports,
		&i.State,
		&i.UpdatedAt,
	)
	return i, err
}

const setWalletChallenge = `-- name: SetWalletChallenge :exec
INSERT INTO wallet_challenges (user_id, address, message, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET address = EXCLUDED.address,
    message = EXCLUDED.message, expires_at = EXCLUDED.expires_at
`

type SetWalletChallengeParams struct {
	UserID    int64              `json:"user_id"`
	Address   string             `json:"address"`
	Message   string             `json:"message"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) SetWalletChallenge(ctx context.Context, arg SetWalletChallengeParams) error {
	_, err := q.db.Exec(ctx, setWalletChallenge,
		arg.UserID,
		arg.Address,
		arg.Message,
		arg.ExpiresAt,
	)
	return err
}

const updateEscrowState = `-- name: UpdateEscrowState :exec
UPDATE post_escrows SET state = $2, updated_at = NOW() WHERE post_id = $1
`

type UpdateEscrowStateParams struct {
	PostID int64  `json:"post_id"`
	State  string `json:"state"`
}

func (q *Queries) UpdateEscrowState(ctx context.Context, arg UpdateEscrowStateParams) error {
	_, err := q.db.Exec(ctx, updateEscrowState, arg.PostID, arg.State)
	return err
}
