// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: offers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAgentOffer = `-- name: GetAgentOffer :one
SELECT user_id, name, description, capabilities, min_lamports, job_timeout_seconds, lease_hash, available_until, accepting, updated_at FROM agent_offers WHERE user_id = $1
`

func (q *Queries) GetAgentOffer(ctx context.Context, userID int64) (AgentOffer, error) {
	row := q.db.QueryRow(ctx, getAgentOffer, userID)
	var i AgentOffer
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Capabilities,
		&i.MinLamports,
		&i.JobTimeoutSeconds,
		&i.LeaseHash,
		&i.AvailableUntil,
		&i.Accepting,
		&i.UpdatedAt,
	)
	return i, err
}

const leaseAgentOffer = `-- name: LeaseAgentOffer :one
UPDATE agent_offers SET lease_hash = $2, accepting = $3,
    available_until = NOW() + INTERVAL '90 seconds', updated_at = NOW()
WHERE user_id = $1 AND (lease_hash = $2 OR available_until IS NULL OR available_until <= NOW())
RETURNING user_id, name, description, capabilities, min_lamports, job_timeout_seconds, lease_hash, available_until, accepting, updated_at
`

type LeaseAgentOfferParams struct {
	UserID    int64  `json:"user_id"`
	LeaseHash string `json:"lease_hash"`
	Accepting bool   `json:"accepting"`
}

func (q *Queries) LeaseAgentOffer(ctx context.Context, arg LeaseAgentOfferParams) (AgentOffer, error) {
	row := q.db.QueryRow(ctx, leaseAgentOffer, arg.UserID, arg.LeaseHash, arg.Accepting)
	var i AgentOffer
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Capabilities,
		&i.MinLamports,
		&i.JobTimeoutSeconds,
		&i.LeaseHash,
		&i.AvailableUntil,
		&i.Accepting,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentOffers = `-- name: ListAgentOffers :many
SELECT o.user_id, o.name, o.description, o.capabilities, o.min_lamports, o.job_timeout_seconds,
    o.available_until, o.updated_at, u.username, u.github_login,
    COALESCE(o.available_until > NOW(), false)::boolean AS online,
    (COALESCE(o.available_until > NOW(), false) AND o.accepting AND NOT EXISTS (SELECT 1 FROM posts p
        WHERE p.accepted_by = o.user_id AND p.status NOT IN ('completed', 'cancelled')))::boolean AS available
FROM agent_offers o JOIN users u ON u.id = o.user_id
ORDER BY COALESCE(o.available_until > NOW(), false) DESC, o.updated_at DESC LIMIT 100
`

type ListAgentOffersRow struct {
	UserID            int64              `json:"user_id"`
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	Capabilities      []string           `json:"capabilities"`
	MinLamports       int64              `json:"min_lamports"`
	JobTimeoutSeconds int64              `json:"job_timeout_seconds"`
	AvailableUntil    pgtype.Timestamptz `json:"available_until"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Username          string             `json:"username"`
	GithubLogin       string             `json:"github_login"`
	Online            bool               `json:"online"`
	Available         bool               `json:"available"`
}

func (q *Queries) ListAgentOffers(ctx context.Context) ([]ListAgentOffersRow, error) {
	rows, err := q.db.Query(ctx, listAgentOffers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentOffersRow
	for rows.Next() {
		var i ListAgentOffersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Capabilities,
			&i.MinLamports,
			&i.JobTimeoutSeconds,
			&i.AvailableUntil,
			&i.UpdatedAt,
			&i.Username,
			&i.GithubLogin,
			&i.Online,
			&i.Available,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAgentOffer = `-- name: LockAgentOffer :one
SELECT user_id, name, description, capabilities, min_lamports, job_timeout_seconds, lease_hash, available_until, accepting, updated_at FROM agent_offers WHERE user_id = $1 FOR UPDATE
`

func (q *Queries) LockAgentOffer(ctx context.Context, userID int64) (AgentOffer, error) {
	row := q.db.QueryRow(ctx, lockAgentOffer, userID)
	var i AgentOffer
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Capabilities,
		&i.MinLamports,
		&i.JobTimeoutSeconds,
		&i.LeaseHash,
		&i.AvailableUntil,
		&i.Accepting,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseAgentOffer = `-- name: ReleaseAgentOffer :execrows
UPDATE agent_offers SET available_until = NULL, accepting = false, lease_hash = ''
WHERE user_id = $1 AND lease_hash = $2
`

type ReleaseAgentOfferParams struct {
	UserID    int64  `json:"user_id"`
	LeaseHash string `json:"lease_hash"`
}

func (q *Queries) ReleaseAgentOffer(ctx context.Context, arg ReleaseAgentOfferParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseAgentOffer, arg.UserID, arg.LeaseHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveAgentOffer = `-- name: SaveAgentOffer :one
INSERT INTO agent_offers (user_id, name, description, capabilities, min_lamports, job_timeout_seconds)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description,
    capabilities = EXCLUDED.capabilities, min_lamports = EXCLUDED.min_lamports,
    job_timeout_seconds = EXCLUDED.job_timeout_seconds, updated_at = NOW()
WHERE agent_offers.available_until IS NULL OR agent_offers.available_until <= NOW()
RETURNING user_id, name, description, capabilities, min_lamports, job_timeout_seconds, lease_hash, available_until, accepting, updated_at
`

type SaveAgentOfferParams struct {
	UserID            int64    `json:"user_id"`
	Name              string   `json:"name"`
	Description       string   `json:"description"`
	Capabilities      []string `json:"capabilities"`
	MinLamports       int64    `json:"min_lamports"`
	JobTimeoutSeconds int64    `json:"job_timeout_seconds"`
}

func (q *Queries) SaveAgentOffer(ctx context.Context, arg SaveAgentOfferParams) (AgentOffer, error) {
	row := q.db.QueryRow(ctx, saveAgentOffer,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Capabilities,
		arg.MinLamports,
		arg.JobTimeoutSeconds,
	)
	var i AgentOffer
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Capabilities,
		&i.MinLamports,
		&i.JobTimeoutSeconds,
		&i.LeaseHash,
		&i.AvailableUntil,
		&i.Accepting,
		&i.UpdatedAt,
	)
	return i, err
}

const workerHasActiveTask = `-- name: WorkerHasActiveTask :one
SELECT EXISTS (SELECT 1 FROM posts WHERE accepted_by = $1 AND status NOT IN ('completed', 'cancelled'))::boolean
`

func (q *Queries) WorkerHasActiveTask(ctx context.Context, acceptedBy pgtype.Int8) (bool, error) {
	row := q.db.QueryRow(ctx, workerHasActiveTask, acceptedBy)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
