// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelUnfundedPost = `-- name: CancelUnfundedPost :one
UPDATE posts SET status = 'cancelled', updated_at = NOW()
WHERE id = $1 AND accepted_by IS NOT NULL AND status = 'negotiating'
RETURNING id, user_id, title, cost_lamports, end_time, status, level, created_at, updated_at, accepted_by, accepted_at, poster_wallet, worker_wallet, description, acceptance_criteria, input_files, expected_outputs, reopened_as, funding_window_seconds, fund_by, deliver_by, review_window_seconds
`

func (q *Queries) CancelUnfundedPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRow(ctx, cancelUnfundedPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CostLamports,
		&i.EndTime,
		&i.Status,
		&i.Level,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedBy,
		&i.AcceptedAt,
		&i.PosterWallet,
		&i.WorkerWallet,
		&i.Description,
		&i.AcceptanceCriteria,
		&i.InputFiles,
		&i.ExpectedOutputs,
		&i.ReopenedAs,
		&i.FundingWindowSeconds,
		&i.FundBy,
		&i.DeliverBy,
		&i.ReviewWindowSeconds,
	)
	return i, err
}

const linkReopenedPost = `-- name: LinkReopenedPost :one
UPDATE posts SET reopened_as = $2, updated_at = NOW()
WHERE id = $1 AND status = 'cancelled' AND reopened_as IS NULL
RETURNING id, user_id, title, cost_lamports, end_time, status, level, created_at, updated_at, accepted_by, accepted_at, poster_wallet, worker_wallet, description, acceptance_criteria, input_files, expected_outputs, reopened_as, funding_window_seconds, fund_by, deliver_by, review_window_seconds
`

type LinkReopenedPostParams struct {
	ID         int64       `json:"id"`
	ReopenedAs pgtype.Int8 `json:"reopened_as"`
}

func (q *Queries) LinkReopenedPost(ctx context.Context, arg LinkReopenedPostParams) (Post, error) {
	row := q.db.QueryRow(ctx, linkReopenedPost, arg.ID, arg.ReopenedAs)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CostLamports,
		&i.EndTime,
		&i.Status,
		&i.Level,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedBy,
		&i.AcceptedAt,
		&i.PosterWallet,
		&i.WorkerWallet,
		&i.Description,
		&i.AcceptanceCriteria,
		&i.InputFiles,
		&i.ExpectedOutputs,
		&i.ReopenedAs,
		&i.FundingWindowSeconds,
		&i.FundBy,
		&i.DeliverBy,
		&i.ReviewWindowSeconds,
	)
	return i, err
}
