// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remote.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRemoteActivity = `-- name: GetRemoteActivity :one
SELECT post_id, run_id, state, detail, active_until, updated_at FROM remote_activity WHERE post_id = $1
`

func (q *Queries) GetRemoteActivity(ctx context.Context, postID int64) (RemoteActivity, error) {
	row := q.db.QueryRow(ctx, getRemoteActivity, postID)
	var i RemoteActivity
	err := row.Scan(
		&i.PostID,
		&i.RunID,
		&i.State,
		&i.Detail,
		&i.ActiveUntil,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteInbox = `-- name: RemoteInbox :many
SELECT p.id, p.user_id, p.title, p.cost_lamports, p.end_time, p.status, p.level, p.created_at, p.updated_at, p.accepted_by, p.accepted_at, p.poster_wallet, p.worker_wallet, p.description, p.acceptance_criteria, p.input_files, p.expected_outputs, p.reopened_as, p.funding_window_seconds, p.fund_by, p.deliver_by, p.review_window_seconds, p.target_worker FROM posts p
WHERE p.user_id = $1 OR p.accepted_by = $1
    OR (p.target_worker = $1 AND p.status = 'open' AND p.end_time > NOW())
    OR EXISTS(SELECT 1 FROM post_escrows e JOIN wallets w ON w.address = e.reviewer
        WHERE e.post_id = p.id AND w.user_id = $1)
ORDER BY (p.status NOT IN ('completed', 'cancelled')) DESC, p.updated_at DESC, p.id DESC LIMIT 100
`

func (q *Queries) RemoteInbox(ctx context.Context, userID int64) ([]Post, error) {
	rows, err := q.db.Query(ctx, remoteInbox, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CostLamports,
			&i.EndTime,
			&i.Status,
			&i.Level,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptedBy,
			&i.AcceptedAt,
			&i.PosterWallet,
			&i.WorkerWallet,
			&i.Description,
			&i.AcceptanceCriteria,
			&i.InputFiles,
			&i.ExpectedOutputs,
			&i.ReopenedAs,
			&i.FundingWindowSeconds,
			&i.FundBy,
			&i.DeliverBy,
			&i.ReviewWindowSeconds,
			&i.TargetWorker,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const remoteSnapshots = `-- name: RemoteSnapshots :many
SELECT p.id, COALESCE(a.state, '')::text AS activity_state,
    COALESCE(a.detail, '')::text AS detail, a.active_until, a.updated_at AS worker_seen,
    COALESCE(w.review_state, '')::text AS review_state,
    COALESCE(w.submission_version, 0)::bigint AS submission_version,
    COALESCE(w.last_event_id, 0)::bigint AS last_event_id,
    COALESCE(e.state, '')::text AS escrow_state,
    o.available_until AS offer_until, COALESCE(o.name, '')::text AS agent_name
FROM posts p
LEFT JOIN remote_activity a ON a.post_id = p.id
LEFT JOIN post_workspaces w ON w.post_id = p.id
LEFT JOIN post_escrows e ON e.post_id = p.id
LEFT JOIN agent_offers o ON o.user_id = COALESCE(p.accepted_by, p.target_worker)
WHERE p.id = ANY($1::bigint[])
`

type RemoteSnapshotsRow struct {
	ID                int64              `json:"id"`
	ActivityState     string             `json:"activity_state"`
	Detail            string             `json:"detail"`
	ActiveUntil       pgtype.Timestamptz `json:"active_until"`
	WorkerSeen        pgtype.Timestamptz `json:"worker_seen"`
	ReviewState       string             `json:"review_state"`
	SubmissionVersion int64              `json:"submission_version"`
	LastEventID       int64              `json:"last_event_id"`
	EscrowState       string             `json:"escrow_state"`
	OfferUntil        pgtype.Timestamptz `json:"offer_until"`
	AgentName         string             `json:"agent_name"`
}

func (q *Queries) RemoteSnapshots(ctx context.Context, dollar_1 []int64) ([]RemoteSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, remoteSnapshots, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemoteSnapshotsRow
	for rows.Next() {
		var i RemoteSnapshotsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActivityState,
			&i.Detail,
			&i.ActiveUntil,
			&i.WorkerSeen,
			&i.ReviewState,
			&i.SubmissionVersion,
			&i.LastEventID,
			&i.EscrowState,
			&i.OfferUntil,
			&i.AgentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRemoteActivity = `-- name: UpdateRemoteActivity :one
INSERT INTO remote_activity(post_id, run_id, state, detail, active_until)
VALUES ($1, $2, COALESCE(NULLIF($3::text, ''), 'starting'),
    $4, CASE WHEN $3::text IN ('waiting_for_review', 'interrupted', 'failed')
        THEN NOW() ELSE NOW() + INTERVAL '90 seconds' END)
ON CONFLICT (post_id) DO UPDATE SET
    run_id = EXCLUDED.run_id,
    state = COALESCE(NULLIF($3::text, ''), remote_activity.state),
    detail = CASE WHEN $3::text = '' THEN remote_activity.detail ELSE EXCLUDED.detail END,
    active_until = CASE WHEN $3::text IN ('waiting_for_review', 'interrupted', 'failed') THEN NOW() ELSE EXCLUDED.active_until END,
    updated_at = NOW()
WHERE remote_activity.run_id = EXCLUDED.run_id OR remote_activity.active_until <= NOW()
RETURNING post_id, run_id, state, detail, active_until, updated_at
`

type UpdateRemoteActivityParams struct {
	PostID int64  `json:"post_id"`
	RunID  string `json:"run_id"`
	State  string `json:"state"`
	Detail string `json:"detail"`
}

func (q *Queries) UpdateRemoteActivity(ctx context.Context, arg UpdateRemoteActivityParams) (RemoteActivity, error) {
	row := q.db.QueryRow(ctx, updateRemoteActivity,
		arg.PostID,
		arg.RunID,
		arg.State,
		arg.Detail,
	)
	var i RemoteActivity
	err := row.Scan(
		&i.PostID,
		&i.RunID,
		&i.State,
		&i.Detail,
		&i.ActiveUntil,
		&i.UpdatedAt,
	)
	return i, err
}
