// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review.sql

package db

import (
	"context"
)

const closeWorkspaceReview = `-- name: CloseWorkspaceReview :exec
UPDATE post_workspaces SET review_state = $2, review_by = NULL
WHERE post_id = $1 AND review_state <> $2
`

type CloseWorkspaceReviewParams struct {
	PostID      int64  `json:"post_id"`
	ReviewState string `json:"review_state"`
}

func (q *Queries) CloseWorkspaceReview(ctx context.Context, arg CloseWorkspaceReviewParams) error {
	_, err := q.db.Exec(ctx, closeWorkspaceReview, arg.PostID, arg.ReviewState)
	return err
}

const getPostSettlement = `-- name: GetPostSettlement :one
SELECT post_id, reviewer_id, action, submission_version, note, transaction, signed_transaction, signature, last_valid_block_height, fee_lamports, state, updated_at FROM post_settlements WHERE post_id = $1
`

func (q *Queries) GetPostSettlement(ctx context.Context, postID int64) (PostSettlement, error) {
	row := q.db.QueryRow(ctx, getPostSettlement, postID)
	var i PostSettlement
	err := row.Scan(
		&i.PostID,
		&i.ReviewerID,
		&i.Action,
		&i.SubmissionVersion,
		&i.Note,
		&i.Transaction,
		&i.SignedTransaction,
		&i.Signature,
		&i.LastValidBlockHeight,
		&i.FeeLamports,
		&i.State,
		&i.UpdatedAt,
	)
	return i, err
}

const isPostReviewer = `-- name: IsPostReviewer :one
SELECT EXISTS(SELECT 1 FROM post_escrows e JOIN wallets w ON w.address = e.reviewer
    WHERE e.post_id = $1 AND w.user_id = $2)::boolean AS allowed
`

type IsPostReviewerParams struct {
	PostID int64 `json:"post_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) IsPostReviewer(ctx context.Context, arg IsPostReviewerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isPostReviewer, arg.PostID, arg.UserID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const markSettlementSubmitted = `-- name: MarkSettlementSubmitted :one
UPDATE post_settlements SET signature = $2, signed_transaction = $3, state = 'pending', updated_at = NOW()
WHERE post_id = $1 AND state = 'prepared' RETURNING post_id, reviewer_id, action, submission_version, note, transaction, signed_transaction, signature, last_valid_block_height, fee_lamports, state, updated_at
`

type MarkSettlementSubmittedParams struct {
	PostID            int64  `json:"post_id"`
	Signature         string `json:"signature"`
	SignedTransaction string `json:"signed_transaction"`
}

func (q *Queries) MarkSettlementSubmitted(ctx context.Context, arg MarkSettlementSubmittedParams) (PostSettlement, error) {
	row := q.db.QueryRow(ctx, markSettlementSubmitted, arg.PostID, arg.Signature, arg.SignedTransaction)
	var i PostSettlement
	err := row.Scan(
		&i.PostID,
		&i.ReviewerID,
		&i.Action,
		&i.SubmissionVersion,
		&i.Note,
		&i.Transaction,
		&i.SignedTransaction,
		&i.Signature,
		&i.LastValidBlockHeight,
		&i.FeeLamports,
		&i.State,
		&i.UpdatedAt,
	)
	return i, err
}

const requestWorkspaceChanges = `-- name: RequestWorkspaceChanges :one
UPDATE post_workspaces SET review_state = 'changes_requested', review_note = $2, review_by = NULL
WHERE post_id = $1 AND review_state = 'submitted' RETURNING post_id, last_event_id, submitted_at, submission, review_state, submission_version, review_note, delivery_files, review_by
`

type RequestWorkspaceChangesParams struct {
	PostID     int64  `json:"post_id"`
	ReviewNote string `json:"review_note"`
}

func (q *Queries) RequestWorkspaceChanges(ctx context.Context, arg RequestWorkspaceChangesParams) (PostWorkspace, error) {
	row := q.db.QueryRow(ctx, requestWorkspaceChanges, arg.PostID, arg.ReviewNote)
	var i PostWorkspace
	err := row.Scan(
		&i.PostID,
		&i.LastEventID,
		&i.SubmittedAt,
		&i.Submission,
		&i.ReviewState,
		&i.SubmissionVersion,
		&i.ReviewNote,
		&i.DeliveryFiles,
		&i.ReviewBy,
	)
	return i, err
}

const savePostSettlement = `-- name: SavePostSettlement :one
INSERT INTO post_settlements (post_id, reviewer_id, action, submission_version, note, transaction, last_valid_block_height, fee_lamports)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (post_id) DO UPDATE SET reviewer_id = EXCLUDED.reviewer_id, action = EXCLUDED.action,
    submission_version = EXCLUDED.submission_version, note = EXCLUDED.note,
    transaction = EXCLUDED.transaction, last_valid_block_height = EXCLUDED.last_valid_block_height,
    fee_lamports = EXCLUDED.fee_lamports, signed_transaction = '', signature = '', state = 'prepared', updated_at = NOW()
WHERE post_settlements.state IN ('failed', 'expired')
RETURNING post_id, reviewer_id, action, submission_version, note, transaction, signed_transaction, signature, last_valid_block_height, fee_lamports, state, updated_at
`

type SavePostSettlementParams struct {
	PostID               int64  `json:"post_id"`
	ReviewerID           int64  `json:"reviewer_id"`
	Action               string `json:"action"`
	SubmissionVersion    int64  `json:"submission_version"`
	Note                 string `json:"note"`
	Transaction          string `json:"transaction"`
	LastValidBlockHeight int64  `json:"last_valid_block_height"`
	FeeLamports          int64  `json:"fee_lamports"`
}

func (q *Queries) SavePostSettlement(ctx context.Context, arg SavePostSettlementParams) (PostSettlement, error) {
	row := q.db.QueryRow(ctx, savePostSettlement,
		arg.PostID,
		arg.ReviewerID,
		arg.Action,
		arg.SubmissionVersion,
		arg.Note,
		arg.Transaction,
		arg.LastValidBlockHeight,
		arg.FeeLamports,
	)
	var i PostSettlement
	err := row.Scan(
		&i.PostID,
		&i.ReviewerID,
		&i.Action,
		&i.SubmissionVersion,
		&i.Note,
		&i.Transaction,
		&i.SignedTransaction,
		&i.Signature,
		&i.LastValidBlockHeight,
		&i.FeeLamports,
		&i.State,
		&i.UpdatedAt,
	)
	return i, err
}

const trackedEscrows = `-- name: TrackedEscrows :many
SELECT e.post_id FROM post_escrows e WHERE e.post_id > $1
    AND (e.state IN ('prepared', 'pending', 'confirmed')
        OR EXISTS(SELECT 1 FROM post_settlements s WHERE s.post_id = e.post_id AND s.state IN ('prepared', 'pending')))
ORDER BY e.post_id LIMIT 20
`

func (q *Queries) TrackedEscrows(ctx context.Context, postID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, trackedEscrows, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var post_id int64
		if err := rows.Scan(&post_id); err != nil {
			return nil, err
		}
		items = append(items, post_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSettlementState = `-- name: UpdateSettlementState :exec
UPDATE post_settlements SET state = $2, updated_at = NOW() WHERE post_id = $1 AND state <> $2
`

type UpdateSettlementStateParams struct {
	PostID int64  `json:"post_id"`
	State  string `json:"state"`
}

func (q *Queries) UpdateSettlementState(ctx context.Context, arg UpdateSettlementStateParams) error {
	_, err := q.db.Exec(ctx, updateSettlementState, arg.PostID, arg.State)
	return err
}
