// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: streams.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const lockWorkspacePublisher = `-- name: LockWorkspacePublisher :one
SELECT pg_try_advisory_xact_lock(73003101)::boolean AS acquired
`

func (q *Queries) LockWorkspacePublisher(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, lockWorkspacePublisher)
	var acquired bool
	err := row.Scan(&acquired)
	return acquired, err
}

const markWorkspaceEventPublished = `-- name: MarkWorkspaceEventPublished :exec
UPDATE workspace_events SET stream_id = $3 WHERE post_id = $1 AND id = $2
`

type MarkWorkspaceEventPublishedParams struct {
	PostID   int64       `json:"post_id"`
	ID       int64       `json:"id"`
	StreamID pgtype.Text `json:"stream_id"`
}

func (q *Queries) MarkWorkspaceEventPublished(ctx context.Context, arg MarkWorkspaceEventPublishedParams) error {
	_, err := q.db.Exec(ctx, markWorkspaceEventPublished, arg.PostID, arg.ID, arg.StreamID)
	return err
}

const unpublishedWorkspaceEvents = `-- name: UnpublishedWorkspaceEvents :many
SELECT post_id, id, actor_id, kind, data, created_at, stream_id FROM workspace_events WHERE stream_id IS NULL ORDER BY post_id, id LIMIT 100 FOR UPDATE
`

func (q *Queries) UnpublishedWorkspaceEvents(ctx context.Context) ([]WorkspaceEvent, error) {
	rows, err := q.db.Query(ctx, unpublishedWorkspaceEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceEvent
	for rows.Next() {
		var i WorkspaceEvent
		if err := rows.Scan(
			&i.PostID,
			&i.ID,
			&i.ActorID,
			&i.Kind,
			&i.Data,
			&i.CreatedAt,
			&i.StreamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workspaceEventStreamID = `-- name: WorkspaceEventStreamID :one
SELECT stream_id FROM workspace_events WHERE post_id = $1 AND id = $2
`

type WorkspaceEventStreamIDParams struct {
	PostID int64 `json:"post_id"`
	ID     int64 `json:"id"`
}

func (q *Queries) WorkspaceEventStreamID(ctx context.Context, arg WorkspaceEventStreamIDParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, workspaceEventStreamID, arg.PostID, arg.ID)
	var stream_id pgtype.Text
	err := row.Scan(&stream_id)
	return stream_id, err
}
