// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkIfUserExist = `-- name: CheckIfUserExist :one
SELECT id, email, google_id, username, avatar, created_at, github_id, github_login FROM users WHERE google_id=$1
`

func (q *Queries) CheckIfUserExist(ctx context.Context, googleID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, checkIfUserExist, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Username,
		&i.Avatar,
		&i.CreatedAt,
		&i.GithubID,
		&i.GithubLogin,
	)
	return i, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (user_id,title,cost_lamports,end_time,status,level,description,acceptance_criteria,input_files,expected_outputs,
    funding_window_seconds, deliver_by, review_window_seconds, target_worker)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, user_id, title, cost_lamports, end_time, status, level, created_at, updated_at, accepted_by, accepted_at, poster_wallet, worker_wallet, description, acceptance_criteria, input_files, expected_outputs, reopened_as, funding_window_seconds, fund_by, deliver_by, review_window_seconds, target_worker
`

type CreatePostParams struct {
	UserID               int64              `json:"user_id"`
	Title                string             `json:"title"`
	CostLamports         int64              `json:"cost_lamports"`
	EndTime              pgtype.Timestamptz `json:"end_time"`
	Status               PostStatus         `json:"status"`
	Level                PostLevel          `json:"level"`
	Description          string             `json:"description"`
	AcceptanceCriteria   string             `json:"acceptance_criteria"`
	InputFiles           []string           `json:"input_files"`
	ExpectedOutputs      []string           `json:"expected_outputs"`
	FundingWindowSeconds int64              `json:"funding_window_seconds"`
	DeliverBy            pgtype.Timestamptz `json:"deliver_by"`
	ReviewWindowSeconds  int64              `json:"review_window_seconds"`
	TargetWorker         pgtype.Int8        `json:"target_worker"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.UserID,
		arg.Title,
		arg.CostLamports,
		arg.EndTime,
		arg.Status,
		arg.Level,
		arg.Description,
		arg.AcceptanceCriteria,
		arg.InputFiles,
		arg.ExpectedOutputs,
		arg.FundingWindowSeconds,
		arg.DeliverBy,
		arg.ReviewWindowSeconds,
		arg.TargetWorker,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CostLamports,
		&i.EndTime,
		&i.Status,
		&i.Level,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedBy,
		&i.AcceptedAt,
		&i.PosterWallet,
		&i.WorkerWallet,
		&i.Description,
		&i.AcceptanceCriteria,
		&i.InputFiles,
		&i.ExpectedOutputs,
		&i.ReopenedAs,
		&i.FundingWindowSeconds,
		&i.FundBy,
		&i.DeliverBy,
		&i.ReviewWindowSeconds,
		&i.TargetWorker,
	)
	return i, err
}

const deleteYourPost = `-- name: DeleteYourPost :execrows
DELETE from posts WHERE user_id=$1 AND id =$2 AND accepted_by IS NULL
`

type DeleteYourPostParams struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
}

func (q *Queries) DeleteYourPost(ctx context.Context, arg DeleteYourPostParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteYourPost, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fetchPostByLevel = `-- name: FetchPostByLevel :many
SELECT id, user_id, title, cost_lamports, end_time, status, level, created_at, updated_at, accepted_by, accepted_at, poster_wallet, worker_wallet, description, acceptance_criteria, input_files, expected_outputs, reopened_as, funding_window_seconds, fund_by, deliver_by, review_window_seconds, target_worker from posts WHERE level=$1 AND user_id<>$2 AND status='open'
    AND accepted_by IS NULL AND end_time > NOW()
    AND (target_worker IS NULL OR target_worker = $2) ORDER BY created_at DESC
`

type FetchPostByLevelParams struct {
	Level  PostLevel `json:"level"`
	UserID int64     `json:"user_id"`
}

func (q *Queries) FetchPostByLevel(ctx context.Context, arg FetchPostByLevelParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, fetchPostByLevel, arg.Level, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CostLamports,
			&i.EndTime,
			&i.Status,
			&i.Level,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptedBy,
			&i.AcceptedAt,
			&i.PosterWallet,
			&i.WorkerWallet,
			&i.Description,
			&i.AcceptanceCriteria,
			&i.InputFiles,
			&i.ExpectedOutputs,
			&i.ReopenedAs,
			&i.FundingWindowSeconds,
			&i.FundBy,
			&i.DeliverBy,
			&i.ReviewWindowSeconds,
			&i.TargetWorker,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUrPosts = `-- name: GetUrPosts :many
SELECT posts.id, posts.user_id, posts.title, posts.cost_lamports, posts.end_time, posts.status, posts.level, posts.created_at, posts.updated_at, posts.accepted_by, posts.accepted_at, posts.poster_wallet, posts.worker_wallet, posts.description, posts.acceptance_criteria, posts.input_files, posts.expected_outputs, posts.reopened_as, posts.funding_window_seconds, posts.fund_by, posts.deliver_by, posts.review_window_seconds, posts.target_worker from posts WHERE posts.user_id=$1 OR posts.accepted_by=$1
    OR EXISTS(SELECT 1 FROM post_escrows e JOIN wallets w ON w.address = e.reviewer
        WHERE e.post_id = posts.id AND w.user_id = $1)
ORDER BY created_at DESC
`

func (q *Queries) GetUrPosts(ctx context.Context, userID int64) ([]Post, error) {
	rows, err := q.db.Query(ctx, getUrPosts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CostLamports,
			&i.EndTime,
			&i.Status,
			&i.Level,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptedBy,
			&i.AcceptedAt,
			&i.PosterWallet,
			&i.WorkerWallet,
			&i.Description,
			&i.AcceptanceCriteria,
			&i.InputFiles,
			&i.ExpectedOutputs,
			&i.ReopenedAs,
			&i.FundingWindowSeconds,
			&i.FundBy,
			&i.DeliverBy,
			&i.ReviewWindowSeconds,
			&i.TargetWorker,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, email, google_id, username, avatar, created_at, github_id, github_login FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Username,
		&i.Avatar,
		&i.CreatedAt,
		&i.GithubID,
		&i.GithubLogin,
	)
	return i, err
}

const linkGitHub = `-- name: LinkGitHub :one
UPDATE users SET github_id = $2, github_login = $3
WHERE id = $1 AND (github_id IS NULL OR github_id = $2)
RETURNING id, email, google_id, username, avatar, created_at, github_id, github_login
`

type LinkGitHubParams struct {
	ID          int64       `json:"id"`
	GithubID    pgtype.Text `json:"github_id"`
	GithubLogin string      `json:"github_login"`
}

func (q *Queries) LinkGitHub(ctx context.Context, arg LinkGitHubParams) (User, error) {
	row := q.db.QueryRow(ctx, linkGitHub, arg.ID, arg.GithubID, arg.GithubLogin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Username,
		&i.Avatar,
		&i.CreatedAt,
		&i.GithubID,
		&i.GithubLogin,
	)
	return i, err
}

const publicUsers = `-- name: PublicUsers :many
SELECT id, username, avatar, github_login FROM users WHERE id = ANY($1::bigint[])
`

type PublicUsersRow struct {
	ID          int64       `json:"id"`
	Username    string      `json:"username"`
	Avatar      pgtype.Text `json:"avatar"`
	GithubLogin string      `json:"github_login"`
}

func (q *Queries) PublicUsers(ctx context.Context, dollar_1 []int64) ([]PublicUsersRow, error) {
	rows, err := q.db.Query(ctx, publicUsers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicUsersRow
	for rows.Next() {
		var i PublicUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Avatar,
			&i.GithubLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerUser = `-- name: RegisterUser :one

INSERT INTO users (email,google_id,username,avatar)
VALUES ($1, $2, $3, $4)RETURNING id, email, google_id, username, avatar, created_at, github_id, github_login
`

type RegisterUserParams struct {
	Email    pgtype.Text `json:"email"`
	GoogleID pgtype.Text `json:"google_id"`
	Username string      `json:"username"`
	Avatar   pgtype.Text `json:"avatar"`
}

// db/queries/users.sql
func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) (User, error) {
	row := q.db.QueryRow(ctx, registerUser,
		arg.Email,
		arg.GoogleID,
		arg.Username,
		arg.Avatar,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Username,
		&i.Avatar,
		&i.CreatedAt,
		&i.GithubID,
		&i.GithubLogin,
	)
	return i, err
}

const signInGitHub = `-- name: SignInGitHub :one
INSERT INTO users (github_id, github_login, username, avatar)
VALUES ($1::text, $2::text,
    $2::text, $3::text)
ON CONFLICT (github_id) DO UPDATE SET github_login = EXCLUDED.github_login,
    avatar = EXCLUDED.avatar
RETURNING id, email, google_id, username, avatar, created_at, github_id, github_login
`

type SignInGitHubParams struct {
	GithubID    pgtype.Text `json:"github_id"`
	GithubLogin string      `json:"github_login"`
	Avatar      pgtype.Text `json:"avatar"`
}

func (q *Queries) SignInGitHub(ctx context.Context, arg SignInGitHubParams) (User, error) {
	row := q.db.QueryRow(ctx, signInGitHub, arg.GithubID, arg.GithubLogin, arg.Avatar)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Username,
		&i.Avatar,
		&i.CreatedAt,
		&i.GithubID,
		&i.GithubLogin,
	)
	return i, err
}

const updatePostStatus = `-- name: UpdatePostStatus :one
UPDATE posts SET status=$1,updated_at=NOW() WHERE id=$2 AND user_id=$3 AND accepted_by IS NULL RETURNING id, user_id, title, cost_lamports, end_time, status, level, created_at, updated_at, accepted_by, accepted_at, poster_wallet, worker_wallet, description, acceptance_criteria, input_files, expected_outputs, reopened_as, funding_window_seconds, fund_by, deliver_by, review_window_seconds, target_worker
`

type UpdatePostStatusParams struct {
	Status PostStatus `json:"status"`
	ID     int64      `json:"id"`
	UserID int64      `json:"user_id"`
}

func (q *Queries) UpdatePostStatus(ctx context.Context, arg UpdatePostStatusParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePostStatus, arg.Status, arg.ID, arg.UserID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CostLamports,
		&i.EndTime,
		&i.Status,
		&i.Level,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedBy,
		&i.AcceptedAt,
		&i.PosterWallet,
		&i.WorkerWallet,
		&i.Description,
		&i.AcceptanceCriteria,
		&i.InputFiles,
		&i.ExpectedOutputs,
		&i.ReopenedAs,
		&i.FundingWindowSeconds,
		&i.FundBy,
		&i.DeliverBy,
		&i.ReviewWindowSeconds,
		&i.TargetWorker,
	)
	return i, err
}
