// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendWorkspaceEvent = `-- name: AppendWorkspaceEvent :one
SELECT workspace_event($1::bigint, $2::bigint,
    $3::text, $4::jsonb)::bigint AS id
`

type AppendWorkspaceEventParams struct {
	PostID  int64           `json:"post_id"`
	ActorID pgtype.Int8     `json:"actor_id"`
	Kind    string          `json:"kind"`
	Data    json.RawMessage `json:"data"`
}

func (q *Queries) AppendWorkspaceEvent(ctx context.Context, arg AppendWorkspaceEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, appendWorkspaceEvent,
		arg.PostID,
		arg.ActorID,
		arg.Kind,
		arg.Data,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT post_id, last_event_id, submitted_at, submission, review_state, submission_version, review_note, delivery_files, review_by FROM post_workspaces WHERE post_id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, postID int64) (PostWorkspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, postID)
	var i PostWorkspace
	err := row.Scan(
		&i.PostID,
		&i.LastEventID,
		&i.SubmittedAt,
		&i.Submission,
		&i.ReviewState,
		&i.SubmissionVersion,
		&i.ReviewNote,
		&i.DeliveryFiles,
		&i.ReviewBy,
	)
	return i, err
}

const getWorkspaceFile = `-- name: GetWorkspaceFile :one
SELECT id, post_id, uploaded_by, name, size, sha256, content, created_at, purpose, agent_grant_id FROM workspace_files WHERE id = $1 AND post_id = $2
`

type GetWorkspaceFileParams struct {
	ID     pgtype.UUID `json:"id"`
	PostID int64       `json:"post_id"`
}

func (q *Queries) GetWorkspaceFile(ctx context.Context, arg GetWorkspaceFileParams) (WorkspaceFile, error) {
	row := q.db.QueryRow(ctx, getWorkspaceFile, arg.ID, arg.PostID)
	var i WorkspaceFile
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UploadedBy,
		&i.Name,
		&i.Size,
		&i.Sha256,
		&i.Content,
		&i.CreatedAt,
		&i.Purpose,
		&i.AgentGrantID,
	)
	return i, err
}

const listWorkspaceEvents = `-- name: ListWorkspaceEvents :many
SELECT post_id, id, actor_id, kind, data, created_at, stream_id FROM workspace_events WHERE post_id = $1 AND id > $2 ORDER BY id LIMIT 100
`

type ListWorkspaceEventsParams struct {
	PostID int64 `json:"post_id"`
	ID     int64 `json:"id"`
}

func (q *Queries) ListWorkspaceEvents(ctx context.Context, arg ListWorkspaceEventsParams) ([]WorkspaceEvent, error) {
	rows, err := q.db.Query(ctx, listWorkspaceEvents, arg.PostID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceEvent
	for rows.Next() {
		var i WorkspaceEvent
		if err := rows.Scan(
			&i.PostID,
			&i.ID,
			&i.ActorID,
			&i.Kind,
			&i.Data,
			&i.CreatedAt,
			&i.StreamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceFiles = `-- name: ListWorkspaceFiles :many
SELECT id, post_id, uploaded_by, name, size, sha256, created_at, purpose, agent_grant_id
FROM workspace_files WHERE post_id = $1 ORDER BY created_at, id
`

type ListWorkspaceFilesRow struct {
	ID           pgtype.UUID        `json:"id"`
	PostID       int64              `json:"post_id"`
	UploadedBy   int64              `json:"uploaded_by"`
	Name         string             `json:"name"`
	Size         int64              `json:"size"`
	Sha256       string             `json:"sha256"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Purpose      string             `json:"purpose"`
	AgentGrantID pgtype.UUID        `json:"agent_grant_id"`
}

func (q *Queries) ListWorkspaceFiles(ctx context.Context, postID int64) ([]ListWorkspaceFilesRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceFiles, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspaceFilesRow
	for rows.Next() {
		var i ListWorkspaceFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UploadedBy,
			&i.Name,
			&i.Size,
			&i.Sha256,
			&i.CreatedAt,
			&i.Purpose,
			&i.AgentGrantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceHistory = `-- name: ListWorkspaceHistory :many
SELECT post_id, id, actor_id, kind, data, created_at, stream_id FROM workspace_events
WHERE post_id = $1 AND ($2::bigint = 0 OR id < $2::bigint)
ORDER BY id DESC LIMIT $3::integer
`

type ListWorkspaceHistoryParams struct {
	PostID   int64 `json:"post_id"`
	BeforeID int64 `json:"before_id"`
	PageSize int32 `json:"page_size"`
}

func (q *Queries) ListWorkspaceHistory(ctx context.Context, arg ListWorkspaceHistoryParams) ([]WorkspaceEvent, error) {
	rows, err := q.db.Query(ctx, listWorkspaceHistory, arg.PostID, arg.BeforeID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceEvent
	for rows.Next() {
		var i WorkspaceEvent
		if err := rows.Scan(
			&i.PostID,
			&i.ID,
			&i.ActorID,
			&i.Kind,
			&i.Data,
			&i.CreatedAt,
			&i.StreamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentWorkspaceEvents = `-- name: RecentWorkspaceEvents :many
SELECT post_id, id, actor_id, kind, data, created_at, stream_id FROM (SELECT post_id, id, actor_id, kind, data, created_at, stream_id FROM workspace_events WHERE post_id = $1 ORDER BY id DESC LIMIT 100) recent ORDER BY id
`

func (q *Queries) RecentWorkspaceEvents(ctx context.Context, postID int64) ([]WorkspaceEvent, error) {
	rows, err := q.db.Query(ctx, recentWorkspaceEvents, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceEvent
	for rows.Next() {
		var i WorkspaceEvent
		if err := rows.Scan(
			&i.PostID,
			&i.ID,
			&i.ActorID,
			&i.Kind,
			&i.Data,
			&i.CreatedAt,
			&i.StreamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveWorkspaceFile = `-- name: SaveWorkspaceFile :exec
INSERT INTO workspace_files (id, post_id, uploaded_by, name, size, sha256, content, purpose, agent_grant_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type SaveWorkspaceFileParams struct {
	ID           pgtype.UUID `json:"id"`
	PostID       int64       `json:"post_id"`
	UploadedBy   int64       `json:"uploaded_by"`
	Name         string      `json:"name"`
	Size         int64       `json:"size"`
	Sha256       string      `json:"sha256"`
	Content      []byte      `json:"content"`
	Purpose      string      `json:"purpose"`
	AgentGrantID pgtype.UUID `json:"agent_grant_id"`
}

func (q *Queries) SaveWorkspaceFile(ctx context.Context, arg SaveWorkspaceFileParams) error {
	_, err := q.db.Exec(ctx, saveWorkspaceFile,
		arg.ID,
		arg.PostID,
		arg.UploadedBy,
		arg.Name,
		arg.Size,
		arg.Sha256,
		arg.Content,
		arg.Purpose,
		arg.AgentGrantID,
	)
	return err
}

const submitWorkspace = `-- name: SubmitWorkspace :one
UPDATE post_workspaces SET submitted_at = NOW(), submission = $2,
    submission_version = submission_version + 1, review_state = 'submitted', review_note = '', delivery_files = $3,
    review_by = CASE WHEN p.review_window_seconds > 0 THEN NOW() + p.review_window_seconds * INTERVAL '1 second' END
FROM posts p
WHERE post_workspaces.post_id = $1 AND p.id = post_workspaces.post_id
    AND review_state IN ('working', 'changes_requested') RETURNING post_workspaces.post_id, post_workspaces.last_event_id, post_workspaces.submitted_at, post_workspaces.submission, post_workspaces.review_state, post_workspaces.submission_version, post_workspaces.review_note, post_workspaces.delivery_files, post_workspaces.review_by
`

type SubmitWorkspaceParams struct {
	PostID        int64         `json:"post_id"`
	Submission    string        `json:"submission"`
	DeliveryFiles []pgtype.UUID `json:"delivery_files"`
}

func (q *Queries) SubmitWorkspace(ctx context.Context, arg SubmitWorkspaceParams) (PostWorkspace, error) {
	row := q.db.QueryRow(ctx, submitWorkspace, arg.PostID, arg.Submission, arg.DeliveryFiles)
	var i PostWorkspace
	err := row.Scan(
		&i.PostID,
		&i.LastEventID,
		&i.SubmittedAt,
		&i.Submission,
		&i.ReviewState,
		&i.SubmissionVersion,
		&i.ReviewNote,
		&i.DeliveryFiles,
		&i.ReviewBy,
	)
	return i, err
}

const workspaceFileBytes = `-- name: WorkspaceFileBytes :one
SELECT COALESCE(SUM(size), 0)::bigint AS size FROM workspace_files WHERE post_id = $1
`

func (q *Queries) WorkspaceFileBytes(ctx context.Context, postID int64) (int64, error) {
	row := q.db.QueryRow(ctx, workspaceFileBytes, postID)
	var size int64
	err := row.Scan(&size)
	return size, err
}
