[toolchain]
anchor_version = "0.32.1"
solana_version = "2.3.13"

[programs.localnet]
maruvo_escrow = "FEV9eR2WC2pPo6RDWEx9iSwvBHfokVpBED246fdUg2hd"

[programs.devnet]
maruvo_escrow = "FEV9eR2WC2pPo6RDWEx9iSwvBHfokVpBED246fdUg2hd"

[provider]
cluster = "Localnet"
wallet = "../../.solana/deployer-keypair.json"
