version: "2"

run:
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - wsl_v5

formatters:
  enable:
    - gofmt
    - golines
  settings:
    golines:
      max-len: 110
  exclusions:
    generated: strict
